import {
    LayoutDashboard,
    BookOpen,
    PenTool,
    Award,
    BarChart2,
    Globe,
    User,
    LogOut,
    Plus,
    Trash2,
    ExternalLink,
    ChevronRight,
    Star,
    Zap,
    CheckCircle,
    AlertCircle,
    Menu,
    X,
    Loader2,
    Calendar,
    Share2,
    ThumbsUp,
    TrendingUp,
    Book,
    Video,
    FileText,
    Github,
    Monitor,
    Database,
    Cpu,
    Bookmark,
    Lock
} from "lucide-react";

export const Icons = {
    Dashboard: LayoutDashboard,
    Topics: BookOpen,
    Logs: PenTool,
    Skills: Award,
    Analytics: BarChart2,
    Feed: Globe,
    User: User,
    Logout: LogOut,
    Add: Plus,
    Delete: Trash2,
    Link: ExternalLink,
    ArrowRight: ChevronRight,
    Star: Star,
    Energy: Zap,
    Check: CheckCircle,
    X: X,
    Close: X,
    Alert: AlertCircle,
    Menu: Menu,
    Spinner: Loader2,
    Calendar: Calendar,
    Share: Share2,
    ThumbsUp: ThumbsUp,
    Trending: TrendingUp,
    // Resource types
    Doc: Book,
    Video: Video,
    Article: FileText,
    Github: Github,
    Course: Monitor,
    Other: ExternalLink,
    Database: Database,
    Cpu: Cpu,
    Bookmark: Bookmark,
    Lock: Lock
};
